name: Build nezha binary

on:
  workflow_dispatch:
    
jobs:
  build:
    name: Build Dashboard
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'naiba/nezha'

      - name: xgo build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.21
          dest: dist
          pkg: cmd/dashboard
          prefix: dashboard
          targets: linux/amd64,linux/arm64,linux/arm-7,linux/s390x,linux/riscv64 # linux/386,
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default

      - name: xgo build static
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.21
          dest: musldist
          pkg: cmd/dashboard
          prefix: dashboard-musl
          targets: linux/amd64,linux/arm64,linux/arm-7,linux/s390x,linux/riscv64 # linux/386,
          v: true
          x: false
          race: false
          ldflags: -s -w --extldflags '-static -fpic'
          buildmode: default
      
      - name: package resource dir
        run: tar czf resource.tar.gz resource

      - name: Upload dist
        uses: actions/upload-artifact@main
        with:
          name: nezha-dashboard
          path: |
              dist
              musldist
              resource.tar.gz

      - name: Generate release tag
        id: tag
        run: echo "release_tag=$(cat service/singleton/singleton.go | grep -oP 'v\d+\.\d+\.\d+')" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
              dist/*
              musldist/*
              resource.tar.gz

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 8

