name: Run Tests

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'naiba/nezha'
      - name: compare versions
        run: |
          export REMOTEVERSION=$(cat service/singleton/singleton.go | grep -oP 'v\d+\.\d+\.\d+')
          export LOCALVERSION=$(curl --location --silent --fail --show-error "https://api.github.com/repos/applexad/nezha-binary-build/releases/latest" | grep -oP '"tag_name":\s*"\K[^"]+')
          wget -qO- https://github.com/applexad/nezha-binary-build/raw/main/compare.sh | bash
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.21.3"
      - name: Unit test
        run: |
          go test -v ./...
      - name: Build test
        run: |
          go build cmd/dashboard/main.go
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: --exclude=G104,G402 ./...
